### ISSUE TITLE
где ExtraSunny_2

### ISSUE THREAD

**Issue by Damierror** [akifle47/InGameTimecycEditor#3]
Используется ли погода ExtraSunny_2 в игре?

**Comment by akifle47** [comment]
нет

**Comment by Damierror** [comment]
Спасибо за старания! Жаль что этот инструмент не появился лет 5-10 назад. Здесь удобно настраивать облака, однако всё остальные параметры за эти годы я настроил в другой программе . Надеюсь эта полезная штука пригодится какому-нибудь талантливому фанату. 
В EditIV у меня вышло 10 неизвестных параметров помимо неиспользуемых и почему то после сохранения в вашем скрипте возникает ошибка при попытке открытия файла в другой программе ,я думаю это связано с изменёнными аннотациями и отрицательными значениями -1 которые я думаю лучше пометить нулями 0.

**Comment by Damierror** [comment]
немного работ
![Снимок экрана (10991)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/4dd59f46-8a7b-48b7-a96a-e9fbecb4d01a)
![Снимок экрана (11247)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/414acf25-c3e6-4db1-8c6c-1de88db47008)
![Снимок экрана (11250)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/c1f68b94-9afd-46f5-bf60-91d0a5f55557)
![Снимок экрана (11267)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/47625594-1235-4177-85e2-8980e174f046)
![Снимок экрана (11561)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/4b158f3b-fc11-4721-93a1-97aff4f576eb)
![Снимок экрана (11586)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/9dc048be-c9a9-41bc-92c2-ae9bcaf09773)
![Снимок экрана (11658)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/4721020b-7498-485a-87eb-d65b1ff1408e)
![Снимок экрана (11660)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/9779ccee-a9da-4fb8-84d0-3b4167a55421)
![Снимок экрана (11667)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/974102e8-d8d4-40d5-b2e3-061ee07f7955)
![Снимок экрана (11879)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/9f74e4a9-09fa-4297-9ea5-f49730f303ad)
![Снимок экрана (12075)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/7d3723ed-adb2-4aa3-9421-06ec2c4037f4)
![Снимок экрана (12179)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/bd00942a-8502-477f-ae5f-3246af378908)
![Снимок экрана (12193)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/1ce907b4-bc43-44a1-9efc-5964bb399ab5)
![Снимок экрана (12230)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/1c4fb38a-9260-499c-b3a9-0875c6853341)
![Снимок экрана (12233)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/13c49743-e6ed-4ae1-bf0e-976bb5817685)
![Снимок экрана (12242)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/ba250b53-02c6-45b9-aa8b-3a0eed5cf6bb)
![Снимок экрана (12250)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/5d7ed42f-114c-44f5-b0b3-bba3c9c42d58)
![Снимок экрана (12255)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/ee23a447-d7eb-44f9-a57b-3b71e523e44d)
![Снимок экрана (12294)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/9e671a83-aa6f-4c10-a1ac-f29371336669)
![Снимок экрана (12364)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/744a2ca4-33f3-4805-8a1a-ee3d8404b0d1)
![Снимок экрана (12367)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/a7ade922-ce60-48fb-b4bf-20826824a7ff)
![Снимок экрана (12371)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/dde0403e-6009-4a3b-926b-7f661e53b4ba)
![Снимок экрана (12386)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/b75b8348-3d06-4949-996d-31803f5aa204)
![Снимок экрана (12411)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/01b68053-b87e-4294-957b-161b2be08aec)
![Снимок экрана (12444)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/f53afb96-df39-495e-ab6d-f12d52f712be)
![Снимок экрана (12450)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/9cc0c1eb-4fed-41d2-998a-f529725ae484)
![Снимок экрана (12456)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/664a1046-8cc2-4ccd-9e6a-78bc676dc48a)
![Снимок экрана (12461)](https://github.com/akifle47/InGameTimecycEditor/assets/146632112/13f54d7e-c028-409f-8a83-71f0ef8fff77)
